name: Automatisation des tests DevSecOps

on:
  push:

jobs:

  Dependances:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Dependances
        run: |
          echo "Contrôle des dépendances"

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances

    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4

      - name: Test Dockerfile
        run: |
          echo "Contrôle du Dockerfile"

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile

    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
